version: "3.7"

services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - "7474:7474"   
      - "7687:7687"   
    environment:
      - NEO4J_AUTH=neo4j/password  
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_useneo4jconfig=true
      - NEO4J_PLUGINS=["apoc", "apoc-extended"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/import  
      - ./plugins:/plugins  